site_name: Freenahi
site_url: https://soragxyz.github.io/freenahi/

repo_url: https://github.com/soragXYZ/freenahi
repo_name: soragXYZ/freenahi
edit_uri: edit/main/docs/docs/


#===================================================================================#
# Theme
#===================================================================================#
theme:
  name: material
  language: en
  favicon: assets/images/safe.png
  icon:
    logo: material/account-cash
    alternate: material/earth
  custom_dir: overrides
  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - content.action.edit
    - content.action.view
    - search.highlight
  
  # System color
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: deep-purple
      scheme: default 
      toggle:
        icon: octicons/sun-16
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      primary: deep-purple
      scheme: slate
      toggle:
        icon: octicons/moon-16
        name: Switch to system preference



#===================================================================================#
# Mkdocs Markdown Extentions, Plugins & extras
#===================================================================================#
markdown_extensions:
  - tables
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: ⚓︎
      permalink_title: Anchor link to this section for reference
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true
          nav_translations:
            Home: Accueil
            What is Freenahi?: Qu'est ce que Freenahi?
            Get started: Démarrer
            Contribute: Contribuer

  - search
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:
      enabled: true
      repository: soragXYZ/goProjectFinancialApp
      branch: main
      docs_path: docs/docs/

extra:
  generator: false

#===================================================================================#
# Mkdocs Navigation Tree
#===================================================================================#
nav:
  - Home: "index.md"
  - What is Freenahi?:
    - WIP: whatIs/WIP.md

  - Get started:
    - WIP: getStarted/WIP.md

  - Backend:
    - Setup: "backend/setup.md"
    - Link: "backend/links.md"  
    - Dependencies: "backend/dependencies.md"

  - Frontend:
    - WIP: frontend/WIP.md

  - Documentation: documentation/documentation.md

  - Contribute: other/contribute.md